name: Post welcome comment  #Workflow name, this name will appear in Actions tab
on:       # allow workflow run
  pull_request: # Workflow will run when pull request opened
    types: [opened]
permissions: # assigns the workflow permissions to operate on the repository
  pull-requests: write   #gives the workflow permission to write to pull requests
